name: shared
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.0
  injectable: ^2.7.1+2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  injectable_generator: ^2.11.1
