name: network
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  pretty_dio_logger: ^1.4.0
  dart_mappable: ^4.6.1

  shared:
    path: ../../shared

  database:
    path: ../database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.11.1
  dart_mappable_builder: ^4.6.3

dependency_overrides:
  analyzer: ^8.2.0
